// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alzmtbnwcwgglqrsbhco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsem10Ym53Y3dnZ2xxcnNiaGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NzQxMTMsImV4cCI6MjA2MTI1MDExM30.Cu0Wt59Jbm_IcFkjSVvx-BkSqMvhQI_OOOg_MsC0Jfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);